language: python

python:
  - "3.4"

sudo: false

services:
  - elasticsearch
  - mysql

before_install:
  - sleep 15
  - pip install flake8
  - pip install coveralls
  - pip install grimoire-elk
  - pip install grimoire-kidash
  - pip install grimoire-reports
  - pip install grimoire-reports
  - pip install httpretty
  - pip install pandas==0.18.1
  - pip install PyMySQL
  - pip install pyyaml
  - pip install sortinghat

# install:
#   - ./setup.py install

script:
  - flake8 .
  - cd tests && ./run_tests.py
