language: python

python:
  - "3.4"

sudo: false

services:
  - elasticsearch
  - mysql

# addons:
#   mariadb: '10.0'

# sleep to wait for Elasticsearch init
before_install:
  - sleep 5
  - pip install flake8
  - pip install coveralls
  - pip install httpretty
  - pip install pandas==0.18.1

install:
  - ./setup.py install

# To avoid: pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
before_script:
  - echo -e "[mysqld]\nmax_allowed_packet=16M" | sudo tee -a /etc/mysql/my.cnf
  - sudo service mysql restart

script:
  - flake8 .
  - cd tests && ./run_tests.py
