language: python

python:
  - "3.4"

sudo: false

services:
  - docker

before_install:
  - docker-compose up -d
  - sleep 25
  - pip install pandas==0.18.1
  - pip install httpretty==0.8.6
  - pip install -r "requirements.txt"
  - pip install flake8
  - pip install coveralls

script:
  - flake8 .
  - cd tests
  - coverage run --source=sirmordred run_tests.py

after_success:
  - coveralls
